repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Update to latest Black version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Update to latest isort version
    hooks:
      - id: isort

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.241
    hooks:
      - id: ruff
        args: ["--fix", "--ignore", "C901"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--in-place", "--remove-unused-variables"]